name: Chase Brown

remote_theme: academicpages/academicpages.github.io

author:
  name: "Chase Brown"
  avatar: "profile.jpg"
  github: "chasealanbrown"
  mastodon:
  - username: chase_brown
    instance: mathstodon.xyz

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

