name: Chase Brown

remote_theme: academicpages/academicpages.github.io

author:
  name: "Chase Brown"
  avatar: "profile.jpg"
  github: "chasealanbrown"
  googlescholar: "https://scholar.google.com/citations?user=qjRD8Z8AAAAJ"
  linkedin: "chase-brown-3a624530"
  mastodon:
  - username: chase_brown
    instance: mathstodon.xyz
  orcid:
  stackoverflow:

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

