name: Chase Brown

remote_theme: academicpages/academicpages.github.io

author:
  name: "Chase Alan Brown"
  email: "chase-brown@ouhsc.edu"
  avatar: "profile.jpg"
  github: "chasealanbrown"
  googlescholar: "https://scholar.google.com/citations?user=qjRD8Z8AAAAJ"
  linkedin: "chase-brown-3a624530"
    #  mastodon:
    #  - username: chase_brown
    #    instance: mathstodon.xyz
    #  orcid:
    #  stackoverflow:
    #
# Reading Files
include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
#  # _teaching
#  - scope:
#      path: ""
#      type: teaching
#    values:
#      layout: single
#      author_profile: true
#      share: true
#      comments: true
#  # _publications
#  - scope:
#      path: ""
#      type: publications
#    values:
#      layout: single
#      author_profile: true
#      share: true
#      comments: true
#  # _portfolio
#  - scope:
#      path: ""
#      type: portfolio
#    values:
#      layout: single
#      author_profile: true
#      share: true
#      comment: true
#  # _talks
#  - scope:
#      path: ""
#      type: talks
#    values:
#      layout: talk
#      author_profile: true
#      share: true

